import { ReactNode } from 'react'
import StyledComponentsRegistry from '../registry';
import { notFound, redirect } from 'next/navigation'
import { NextIntlClientProvider } from 'next-intl'
import Header from '../../components/Link'
import { isValidLocale, locales } from '../../utils/i18n'

export const metadata = {
  title: 'Welcome to demo2',
  description: 'Generated by create-nx-workspace',
};

type LocaleRootLayoutProps = {
  children: ReactNode
  params: { locale: string }
}

async function getMessages(locale: string) {
  try {
    return (await import(`../../messages/${locale}.json`)).default
  } catch (error) {
    notFound()
  }
}

export async function generateStaticParams() {
  return locales.map((locale) => ({ locale }))
}

export default async function LocaleRootLayout({
  children,
  params: { locale },
}: LocaleRootLayoutProps) {
  console.log('locale', locale)
  if (!isValidLocale(locale)) {
    redirect(`/${locales[0]}`)
  }
  const messages = await getMessages(locale)

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Header />
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
